# https://taskfile.dev

version: '3'

tasks:
  venv:
    cmds:
      - python3 -m venv venv/
      - source venv/bin/activate && pip3 install conan
    status:
      - test -d venv/

  ctags:
    deps: [venv]
    cmds:
      - source venv/bin/activate && ./ctags-gen.sh

  conan-profile:
    deps: [venv]
    cmds:
      - source venv/bin/activate && conan profile detect --force
    status:
      - test -f CMakeUserPresets.json

  conan-install-debug:
    deps: [conan-profile]
    cmds:
      - source venv/bin/activate && conan install . --settings=build_type=Debug --build="*"
    status:
      - test -d build/Debug

  conan-install-release:
    deps: [conan-profile]
    cmds:
      - source venv/bin/activate && conan install . --settings=build_type=Release --build="*"
    status:
      - test -d build/Release

  conan-build-debug:
    deps: [conan-install-debug]
    cmds:
      - source venv/bin/activate && conan build . --settings=build_type=Debug --build="*"
    status:
      - test -d build/Debug

  test-debug:
    deps: [cmake-build-debug]
    cmds:
      - ctest --preset conan-debug --output-on-failure --no-tests=error
      # - ctest --preset conan-debug --verbose --no-tests=error

  cmake-build-debug:
    deps: [conan-build-debug]
    cmds:
      - cmake --build build/Debug

  conan-build-release:
    deps: [conan-install-release]
    cmds:
      - source venv/bin/activate && conan build . --settings=build_type=Release --build="*"

  cmake-install:
    deps: [conan-build-release]
    cmds:
      - cmake --install build/Release --prefix dist/

  clean:
    cmds:
      - rm -rf build/
      - rm -rf dist/

  default:
    cmds:
      - task: cmake-install
